config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  skip: [:session, :password, :registration, :configuration], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope "(:locale)", locale: /ru|en/ do 
    devise_for :users,  skip: :omniauth_callbacks
    get 'userlist/index'
    resources :tags
    resources :colls
    resources :colls do
      resources :items
    end
    resources :colls do
      resources :dops
    end
    resources :items do
      #post 'comments', to: 'comments#create'
      resources :comments, only: [:create, :destroy] 
    end

      resources :dops do
        resources :dopplaces
  end
    resources :colls do
      member do
        put "like" => "colls#upvote"
        put "unlike" => "colls#downvote"
      end
    end
    delete " /users(.:format)", to: "devise/registrations#update" , as: :user_path
    delete "/%20/users(.:format)", to: "users#index" , as: :users_path_path
    put "/users/:id(.:format)", to: "users#update", as: :update_users


    root to: "home#index"
    get	'/colls/:coll_id/items/:id(.:format)', to: "items#show", as: :coll_item_path
    get '/colls/:coll_id/dops/:id(.:format)', to: "dops#show", as: :coll_dop_path


    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :users
    get 'users/:id' => 'users#show'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
end

app/models/coll.rb
class Coll < ApplicationRecord
    acts_as_votable
    has_many :dops ,dependent: :destroy
    has_many :items, dependent: :destroy
    belongs_to :user
    has_many :dop
    validates_length_of :title, maximum: 30, allow_blank: true
    validates_length_of :body, minimum: 10, allow_blank: true
    validates  :title, presence: true
    validates  :image, presence: true
    validates  :body, presence: true
    has_one_attached :image

    has_many :topiccing , dependent: :destroy
    has_many :topic , through: :topiccing
   def all_topics=(names)
    self.topic = names.split(',').map do |name|
      Topic.where(name: name).first_or_create!
  end
end
def all_topics
  topic.map(&:name).join(",")
end

def self.search(search)
  if search
    self.where("title like ?", "%#{search}%")
  else
    self.all
  end
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item

end

app/models/dop.rb
class Dop < ApplicationRecord
  belongs_to :coll
  belongs_to :user
  has_many :dopplace


end

app/models/dopplace.rb
class Dopplace < ApplicationRecord
    belongs_to :dop
    belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :coll
  has_many :dopplaces
  has_many :taggings , dependent: :destroy
  has_many :tags , through: :taggings
  has_one_attached :image
  validates  :image, presence: true


  def all_tags
    self.tags.map(&:name).join(', ')
    end
    
    def all_tags=(names)
    self.tags = names.split(',').map do |name|
    Tag.where(name: name.strip).first_or_create!
    end
    end
  end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings, dependent: :destroy
    has_many :items, through: :taggings
    def self.counts
        self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
        end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :topiccing, dependent: :destroy
    has_many :colls, through: :topiccing
end

app/models/topiccing.rb
class Topiccing < ApplicationRecord
  belongs_to :coll
  belongs_to :topic
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
         has_many :colls
         has_many :dops
         devise :omniauthable, omniauth_providers: [:facebook, :github]

   
     
          def active_for_authentication?
            super && !deactivated
          end

          def self.from_omniauth(auth)
            if @email = auth.info.email
              where(email: @email).first_or_create do |user|
                user.provider = auth.provider
                user.uid = auth.uid
                user.password = Devise.friendly_token[0, 20]
                user.name = auth.info.name   # assuming the user model has a name
              end
            else
               where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
                 user.email = "no@email"
                 user.password = Devise.friendly_token[0, 20]
                 user.name = auth.info.name   # assuming the user model has a name
               end
            end
        end
      end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @colls = Coll.all
    @tags = Tag.all
    @items = Item.all.order(created_at: :desc).limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(body)
        renderer = Redcarpet::Render::HTML.new(harp_wrap: true, filter_html: true)
        options = {
           autolink: true,
           no_intra_emphasis: true,
           disable_indented_code_blocks: true,
           fenced_code_blocks: true,
           lax_html_blocks: true,
           strikethrough: true,
           superscript: true
        }
        Redcarpet::Markdown.new(renderer, options).render(body).html_safe
    end
end

app/helpers/colls_helper.rb
module CollsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dopplaces_helper.rb
module DopplacesHelper
end

app/helpers/dops_helper.rb
module DopsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    
    def tag_cloud(tags)
        max = tags.sort_by(&:count).last
        tags.each do |tag|
        yield(tag)
        end
    end

end


        

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/userlist_helper.rb
module UserlistHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<style>

     .box1 { 
       background: #f0f0f0; 
      
       padding: 40px; 
       height: 4000px;
       margin: 0px;
       margin-top:80px;
       box-shadow: 0 0 10px black ;  }
     .card {
      display:inline-block;
      margin-left:60px;
      transition: .5s;
      box-shadow: 0 0 10px black; 
      margin-top: 50px;} 
    .card:hover{
        transform: translate(-10px,-10px);
        box-shadow: 10px 10px 15px ; }
        .alltags{
          margin-left:50%;
        }
      
</style>






  
   <div class="box1">  
    
   

   <div class="alert alert-success" role="alert">
    <h4 class="alltags"><%= t('home.allT') %></h4>
 
     
    <% tag_cloud(Tag.counts) do |tag| %>
    <%= link_to tag.name, tag_path(tag.name) %>
   <%end%>


   

   </div>
    <div>
    <h2><%= t('home.lastI') %></h2>
  
  <% @items.each do |item|%>
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
    <% if item.image.attached?%>
      <img class="card-img-top"<%=image_tag(item.image)%>
      <%end%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%=item.title%></h5>
        <p class="card-text"><%=item.body%></p>
        <p class="card-text"><%= t('home.cOll')%><small class="text-muted"><%=item.coll.title %></small></p>
        
      </div>
    </div>
  </div>
</div>


<%end%>
</div>

<div>
<h2><%= t('home.Coll')%></h2>
     <% @colls.each do |coll| %>
      <% if coll%>
   <div class="card" style="width : 18rem;">
         <% if coll.image.attached?%>
          <img class="card-img-top"<%=image_tag(coll.image)%>
          <% end %>
   <div class="card-body">
          <h5 class="card-title"><%=coll.title%></h5>
         
          <%=link_to like_coll_path(coll),class: "like", method: :put do %>
           <button type="button" class="btn btn-info" aria-label="left Align">
           <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
           <span class="badge"><%=coll.get_upvotes.size%></span>
           </button>
           <% end %>
           
             <%=link_to unlike_coll_path(coll),class: "like", method: :put do %>
           <button type="button" class="btn btn-dark" aria-label="left Align">
           <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
           <span class="badge"><%=coll.get_downvotes.size%></span>
           </button>
           <% end %>
            <a class="btn btn-primary"<%= link_to t('home.ShowC'), coll_path(coll) %>  </a> 
       </div>    
</div> 

<%end%>
<% end %>
  </div>