config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  skip: [:session, :password, :registration, :configuration], controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope "(:locale)", locale: /ru|en/ do 
    devise_for :users,  skip: :omniauth_callbacks
    get 'userlist/index'
    resources :tags
    resources :colls
    resources :colls do
      resources :items
    end
    resources :colls do
      resources :dops
    end
    resources :items do
      #post 'comments', to: 'comments#create'
      resources :comments, only: [:create, :destroy] 
    end

      resources :dops do
        resources :dopplaces
  end
    resources :colls do
      member do
        put "like" => "colls#upvote"
        put "unlike" => "colls#downvote"
      end
    end
    delete " /users(.:format)", to: "devise/registrations#update" , as: :user_path
    delete "/%20/users(.:format)", to: "users#index" , as: :users_path_path
    put "/users/:id(.:format)", to: "users#update", as: :update_users


    root to: "home#index"
    get	'/colls/:coll_id/items/:id(.:format)', to: "items#show", as: :coll_item_path
    get '/colls/:coll_id/dops/:id(.:format)', to: "dops#show", as: :coll_dop_path


    
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :users
    get 'users/:id' => 'users#show'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
end

app/models/coll.rb
class Coll < ApplicationRecord
    acts_as_votable
    has_many :dops ,dependent: :destroy
    has_many :items, dependent: :destroy
    belongs_to :user
    has_many :dop
    validates_length_of :title, maximum: 30, allow_blank: true
    validates_length_of :body, minimum: 10, allow_blank: true
    validates  :title, presence: true
    validates  :image, presence: true
    validates  :body, presence: true
    has_one_attached :image

    has_many :topiccing , dependent: :destroy
    has_many :topic , through: :topiccing
   def all_topics=(names)
    self.topic = names.split(',').map do |name|
      Topic.where(name: name).first_or_create!
  end
end
def all_topics
  topic.map(&:name).join(",")
end

def self.search(search)
  if search
    self.where("title like ?", "%#{search}%")
  else
    self.all
  end
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item

end

app/models/dop.rb
class Dop < ApplicationRecord
  belongs_to :coll
  belongs_to :user
  has_many :dopplace


end

app/models/dopplace.rb
class Dopplace < ApplicationRecord
    belongs_to :dop
    belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :coll
  has_many :dopplaces
  has_many :taggings , dependent: :destroy
  has_many :tags , through: :taggings
  has_one_attached :image
  validates  :image, presence: true


  def all_tags
    self.tags.map(&:name).join(', ')
    end
    
    def all_tags=(names)
    self.tags = names.split(',').map do |name|
    Tag.where(name: name.strip).first_or_create!
    end
    end
  end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings, dependent: :destroy
    has_many :items, through: :taggings
    def self.counts
        self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
        end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :topiccing, dependent: :destroy
    has_many :colls, through: :topiccing
end

app/models/topiccing.rb
class Topiccing < ApplicationRecord
  belongs_to :coll
  belongs_to :topic
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
         has_many :colls
         has_many :dops
         devise :omniauthable, omniauth_providers: [:facebook, :github]

   
     
          def active_for_authentication?
            super && !deactivated
          end

          def self.from_omniauth(auth)
            if @email = auth.info.email
              where(email: @email).first_or_create do |user|
                user.provider = auth.provider
                user.uid = auth.uid
                user.password = Devise.friendly_token[0, 20]
                user.name = auth.info.name   # assuming the user model has a name
              end
            else
               where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
                 user.email = "no@email"
                 user.password = Devise.friendly_token[0, 20]
                 user.name = auth.info.name   # assuming the user model has a name
               end
            end
        end
      end

app/controllers/colls_controller.rb
class CollsController < ApplicationController
  before_action :set_coll, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:show , :index]
  

  # GET /colls
  # GET /colls.json
  def index
    @colls = Coll.search(params[:search])
  end

  # GET /colls/1
  # GET /colls/1.json
  def show
   @dop = Dop.new
   @dops = @coll.dops.order("created_at DESC")
  end

  # GET /colls/new
  def new
    @coll = Coll.new
  end

  # GET /colls/1/edit
  def edit
  end

  # POST /colls
  # POST /colls.json
  def create
    @coll = Coll.new(coll_params)
    @coll.user_id = current_user.id

    respond_to do |format|
      if @coll.save
        format.html { redirect_to @coll, notice: 'Coll was successfully created.' }
        format.json { render :show, status: :created, location: @coll }
      else
        format.html { render :new }
        format.json { render json: @coll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colls/1
  # PATCH/PUT /colls/1.json
  def update
    respond_to do |format|
      if @coll.update(coll_params)
        format.html { redirect_to @coll, notice: 'Coll was successfully updated.' }
        format.json { render :show, status: :ok, location: @coll }
      else
        format.html { render :edit }
        format.json { render json: @coll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colls/1
  # DELETE /colls/1.json
  
  def destroy
    @coll.destroy
    respond_to do |format|
      format.html { redirect_to colls_url, notice: 'Coll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @coll.upvote_by current_user
    redirect_to root_path
  end

  def downvote
    @coll.downvote_by current_user
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coll
      @coll = Coll.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coll_params
      params.require(:coll).permit(:title, :body, :all_topics, :image)
    end
end

app/controllers/dops_controller.rb
class DopsController < ApplicationController


  def index
    @dops = Dop.all
  end

  def show 
      @dop = Dop.find(params[:coll_id])
    end

    def create
      @coll = Coll.find(params[:coll_id])
        @dop = @coll.dops.new(dop_params)
        @dop.user_id = current_user.id
        @dop.save
        redirect_back(fallback_location: coll_path(@coll))
    end

      private
        def dop_params
          params.require(:dop).permit(:tfield, :name)
        end
    end
    

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(body)
        renderer = Redcarpet::Render::HTML.new(harp_wrap: true, filter_html: true)
        options = {
           autolink: true,
           no_intra_emphasis: true,
           disable_indented_code_blocks: true,
           fenced_code_blocks: true,
           lax_html_blocks: true,
           strikethrough: true,
           superscript: true
        }
        Redcarpet::Markdown.new(renderer, options).render(body).html_safe
    end
end

app/helpers/colls_helper.rb
module CollsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dopplaces_helper.rb
module DopplacesHelper
end

app/helpers/dops_helper.rb
module DopsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    
    def tag_cloud(tags)
        max = tags.sort_by(&:count).last
        tags.each do |tag|
        yield(tag)
        end
    end

end


        

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/userlist_helper.rb
module UserlistHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/colls/_form.html.erb
<style>
.fieldimage{
 height:100px;
 width:400px;
 border: 2px black dotted;
}

</style>

     <%= render 'home/style'%>
    <%=render 'layouts/style'%>

    

<%= form_with(model: coll, local: true) do |form| %>
  <% if coll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coll.errors.count, "error") %> prohibited this coll from being saved:</h2>

      <ul>
        <% coll.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
   <%=form.label :all_topics %>
    <select class="form-control form-control-lg" <%= form.select :all_topics, options_for_select([[ t('common.selectT'), ""], t('common.sAuto'), t('common.sWork'),t('common.sBeverages'),t('common.sBooks'), t('common.sMinerals'),
    t('common.sAnimals'),t('common.sArt'),t('common.sClothing')]), :class => 'form-control form-control-lg' %></select>
  </div>


  <div class="form-group">
    <%=form.label :title %>
     <textarea class="form-control" id="exampleFormControlTextarea1" rows="2"  <%= form.text_area :title %></textarea>
  </div>


  <div class="form-group formimage">  
    <%=form.label :image %>
   <input class="fieldimage" <%=form.file_field :image%></input>
  </div>
   
  <div class="form-group">
  <%=form.label :body%>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"  <%= form.text_area :body %></textarea>
  </div>


  <div class="form-group">
     
     <button type="submit" class="btn btn-primary btn-lg btn-block" ><%=t('common.createC')%></button>
     
  </div>
<% end %>

app/views/colls/edit.html.erb
<style>
.box1 { 
       background: #f0f0f0; 
       
       padding: 40px; 
       height: 4000px;
       margin: 0px;
       margin-top:80px;
       box-shadow: 0 0 10px black ;  }
       .form-control{
     border: 1px solid black;
   }
       </style>
       <div class="box1">



<%= link_to t('clEd.Show'), @coll %> |
<%= link_to t('clEd.Back'), colls_path %>
</div>

app/views/colls/index.html.erb
<style>

     .box1 { 
       background: #f0f0f0; 
       
       padding: 40px; 
       height: 4000px;
       margin: 0px;
       margin-top:80px;
       box-shadow: 0 0 10px black ;
       margin-top: 50px;  }
     .card {
      display:inline-block;
      margin-left:60px;
      margin-top: 100px;
      transition: .5s;
      box-shadow: 0 0 10px black;
      margin-top: 50px;  } 
    .card:hover{
        transform: translate(-10px,-10px);
        box-shadow: 10px 10px 15px ; }
                 .info {
    
    padding: 10px;
    word-wrap:break-word;
    display: block;
    margin-left: 100px;

    font-family: 'Anton', sans-serif;
    font-family: 'Play', sans-serif;
    font-size: 30px;
   }
       </style>




<div class="box1">
 
  <p class='info'>ID:
  <%= current_user.id %>
 </p>
  <P class='info'><%=t('prof.Email')%>
  <%= current_user.email %>
  </P>
  <P class='info'><%=t('prof.Data')%>
  <%= current_user.created_at %>
  </P>
  <P class='info'><%=t('prof.DataUp')%>
  <%= current_user.updated_at %>
  </P>



     <% @colls.each do |coll| %>
         <% if current_user.id == coll.user_id%> 
   <div class="card" style="width : 18rem;">
         <% if coll.image.attached?%>
          <img class="card-img-top"<%=image_tag(coll.image)%>
          <% end %>
          <div class="card-body">
          <h5 class="card-title"><%=coll.title%></h5>
         
                    <%=link_to like_coll_path(coll),class: t('prof.ShowC'), method: :put do %>
           <button type="button" class="btn btn-info" aria-label="left Align">
           <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
           <span class="badge"><%=coll.get_upvotes.size%></span>
           </button>
           <% end %>
             <%=link_to unlike_coll_path(coll),class: "like", method: :put do %>
           <button type="button" class="btn btn-dark" aria-label="left Align">
           <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
           <span class="badge"><%=coll.get_downvotes.size%></span>
           </button>
           <% end %>
            <a class="btn btn-primary"<%= link_to t('prof.ShowC'), coll_path(coll) %>  </a> 
</div> 
</div>
<%end%>
<%end%>
</div> 





<% if user_signed_in? %>
   <a style="right: 28px;top: 200px;position: absolute; color: white;"class="btn btn-warning" <%= link_to t('prof.NewC'), new_coll_path %> </a>
<% if current_user.admin?%>
   <a style="right: 28px;top: 270px;position: absolute; color: white;"class="btn btn-danger" <%= link_to t('prof.UsList'), userlist_index_path %> </a>
<%end%>
<%end%>

app/views/colls/new.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<style>
.box1 { 
       background: #f0f0f0; 
       
       padding: 40px; 
       height: 4000px ;
       margin: 0px;
       margin-top:80px;
       box-shadow: 0 0 10px black ;  }
       </style>
       <div class="box1">

<%= render 'form', coll: @coll %>

<a class="btn btn-dark" <%= link_to t('common.nBack'), colls_path %></a>



</div>

app/views/colls/show.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
 <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<style>
.box1 { 
       background: #f0f0f0; 
       padding: 40px; 
       height: 4000px;
       box-shadow: 0 0 10px black ;  }
        h1 {
    border: 1px solid black;
    padding: auto;
    word-wrap:break-word;
    display: block;
    background-color: #ffffff;
    border-radius: 6px;
    text-align: center;
    font-family: 'Anton', sans-serif;
    font-family: 'Play', sans-serif;
    font-size: 20px;
    width: 400px;
  
   }
 
   .form123 {
     display:none;  
   }
   .form_add_field {
     display:none;

   }
   .btn-item {
      left: 10px;  
   }
   .fieldimage{
     display: flex;
    margin-top: 10px;
     border: 2px black dotted;
 height:100px;
 width:400px;
 }

 .iteminfo{
   font-size:20px;
   color:black;
 }
   
 
       </style>
       


       
      
       
<div  class="box1">

<div class="alert alert-dark" role="alert">
  <%=t('showC.Topic')%><%=@coll.all_topics%>
</div>

<p id="notice"><%= notice %></p>
<div class="d-flex flex-column">

<% if @coll.image.attached?%>

  <div style="width:400px; height:auto;" class = "imagecoll" >
<%=image_tag(@coll.image,style:'width:100%')%>
</div>
<% end %>




<h1 class="h-100 mt-3">
  <strong><%= markdown @coll.title %>:</strong>

  <%=markdown @coll.body %>

</h1>

</div>



<% if user_signed_in?%>
<a style="right: 50px;top: 210px;position: absolute; color: white;"  class="btn btn-dark", color="white"<%= link_to t('showC.Back'), colls_path %> </a>

<% if current_user.admin? || current_user.id == @coll.user_id %> 
<a style="right: 198px;top: 210px;position: absolute; color: white;" class="btn btn-info", color="white"<%= link_to t('showC.Edit'), edit_coll_path(@coll) %> </a>
<a style="right: 324px;top: 210px;position: absolute; color: white;" class="btn btn-danger", color="white"<%= link_to t('showC.Delete'), @coll_path, method: :delete %></a>

 <%end%>
  <%end%>







 
  <table  class="table table-striped w-auto">
  
  
  <tbody>
    <tr> 
    <% @coll.items.each do |item|%>

      <td><p class="iteminfo"><%=item.id%></p></th>
      <td><p class="iteminfo"><%= item.title%></p></td>
      <td><p class="iteminfo"><%=item.body %></p></td>
      
      <td><%= item.created_at%></td>
      <% if user_signed_in?%>
     <% if current_user.admin? || current_user.id == @coll.user_id %> 
      <td><a class="btn btn-outline-danger"<%= link_to t('showC.delIt'), [item.coll, item],
               method: :delete,
               data: { confirm: 'Are you sure?' } %></a></td>
               <td><a class="btn btn-outline-success"<%=link_to t('showC.shIt'),item_path(item) %> </a> </td>
    </tr>
    <% end %>
    <% end %>
    </tbody>
    <% end %>
    </table>
    


    <% if user_signed_in?%>
    <% if current_user.admin? || current_user.id == @coll.user_id %> 
    <button  class="btn btn-info add-item" ><%=t('showC.CrIt')%></button>
<%=  form_with(model: [ @coll, @coll.items.build ], local: true) do |form| %>
  <div class = 'form123'>
<div class="form-group">
  <input  class="fieldimage" <%=form.file_field :image%></input>
  </div>
  <div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-default"><%=t('showC.addTitle')%></span>
  </div>
     <textarea class="form-control" id="exampleFormControlTextarea1" rows="1" <%= form.text_field :title %></textarea>
  </div>
   <div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-default"><%=t('showC.addBody')%></span>
  </div>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="2" <%= form.text_area :body %></textarea>
  </div>
   
   <p>
   <div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-default"><%=t('showC.addTags')%></span>
  </div>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="1"  <%= form.text_field :all_tags%></textarea>
</div>









   <p>
<button type="submit" class="btn btn-success "><%=t('showC.btCrIt')%></button>
</p>
</div>
<% end %>
<% end %>
<script>
$( ".add-item" ).click(function() {
  $( ".form123" ).slideToggle( "slow" );
});
</script>
 <% end %>

 <div id="show-dop" style="display:none;" > </div>


</div>